In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4])

print('Number of elements: ', x.size)
print('Shape of the array', x.shape)
print('Number of dimensions', x.ndim)

Number of elements:  4
Shape of the array (4,)
Number of dimensions 1


In [3]:
x

array([1, 2, 3, 4])

In [4]:
x = np.array([[1,2,3], [4,5,6]])

print('Number of elements: ', x.size)
print('Shape of the array', x.shape)
print('Number of dimensions', x.ndim)

Number of elements:  6
Shape of the array (2, 3)
Number of dimensions 2


In [5]:
print(x.dtype)

int64


In [6]:
x_f64 = x.astype("float64")
print(x_f64.dtype)

float64


In [7]:
X = np.array([[1,2,3], [4,5,6]], dtype='float64')
print(X.dtype)

float64


In [8]:
x = np.arange(20)

In [9]:
x[1:10:2]

array([1, 3, 5, 7, 9])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [16]:
np.diag([1,2,3], k=1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [17]:
np.arange(10) # array with regularly incremented values.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(2,9,2) # start, end, step

array([2, 4, 6, 8])

In [19]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
q = np.arange(12)
q1 = q.reshape(3,4)

In [21]:
print(q)
print(q1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [22]:
q[0] = 12
print(q)
print(q1)

[12  1  2  3  4  5  6  7  8  9 10 11]
[[12  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
np.random.rand(4,5) # Random numbers from uniform distribution in [0,1]

array([[0.21901399, 0.43147979, 0.3921929 , 0.19097273, 0.27291572],
       [0.79135409, 0.11882706, 0.33708274, 0.70569516, 0.25427012],
       [0.99524579, 0.83165785, 0.37353584, 0.73342655, 0.01921219],
       [0.13580545, 0.5807071 , 0.78176953, 0.15274955, 0.75040548]])

In [24]:
np.random.randn(4) # Random numbers from standard normal distribution: mean 0, std 1

array([0.58683092, 0.94267826, 1.45536098, 0.01885713])

In [25]:
x = np.arange(10)
print(x)
print(x[0]) # it is 0-based i.e. indexing starts from zero
print(x[-2]) # negative indices for indexing from the end of the array

[0 1 2 3 4 5 6 7 8 9]
0
8


In [26]:
x = np.arange(12).reshape(2,2,3)
print(x, "\n ------")
print(x[1], "\n ------") # x[1,:,:]
print(x[1][0], "\n ------") # equivalent to x[1,0,:]
print(x[1][0][0], "\n ------") # equivalent to x[1,0,0]

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] 
 ------
[[ 6  7  8]
 [ 9 10 11]] 
 ------
[6 7 8] 
 ------
6 
 ------


In [27]:
a = np.array([1, 2, 3, 4])
b = a*2

print("multiplication by a scalar:", b)
print("Sum elementwise: ", a + b)
print("Diff elementwise: ", a - b)
print("Multiplication elementwise: ", a*b)

multiplication by a scalar: [2 4 6 8]
Sum elementwise:  [ 3  6  9 12]
Diff elementwise:  [-1 -2 -3 -4]
Multiplication elementwise:  [ 2  8 18 32]


In [28]:
v = np.array([1,0])
w = np.array([2,2])
print("inner product of 2 vectors: ", np.dot(v,w))

inner product of 2 vectors:  2


In [29]:
x = np.array([[0, 1, 0], [1, 0, 0]])
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x, "\n ------")
print(y, "\n ------")
print(f"multiplication of {x.shape} by {y.shape} ndarray matrices: \n", np.dot(x,y))

[[0 1 0]
 [1 0 0]] 
 ------
[[1 2 3]
 [4 5 6]
 [7 8 9]] 
 ------
multiplication of (2, 3) by (3, 3) ndarray matrices: 
 [[4 5 6]
 [1 2 3]]


In [30]:
print("max of the whole array: ", np.max(y))
print("max value along axis 0: ", np.max(y, axis=0))
print("max value along axis 1: ", np.max(y, axis=1))

max of the whole array:  9
max value along axis 0:  [7 8 9]
max value along axis 1:  [3 6 9]


In [31]:
xT = x.T
print(xT)

[[0 1]
 [1 0]
 [0 0]]


In [32]:
xT = np.transpose(x)
print(xT)

[[0 1]
 [1 0]
 [0 0]]


In [33]:
x_flat = x.flatten()
print(x_flat)

[0 1 0 1 0 0]
